[[redirects]]
  from = "/admin/*"
  to = "https://rera-os-admin-web-rerastreat.vercel.app/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/events/*"
  to = "/events.html"
  status = 200
